camera_config: "/home/jan/CORNputer-vision_deployed/data_capture/configs/example.json"
# camera_config: "" # no camera config
save_path: "/home/jan/datasets/examples/405"

# rgb images
rgb_width: 640
rgb_height: 480
fps_rgb: 30

# depth images
depth_width: 640
depth_height: 480
fps_depth: 30

align: True

# post processing for depth images / background removal
clip_dist: 0.3
background_color: 0
post_process_depth: True  
decimation:
  enabled: False
  magnitude: 4
spatial:
  enabled: True
  magnitude: 5
  alpha: 1
  delta: 50
  hole_filling: 3
temporal:
  enabled: True
  alpha: 0.4
  delta: 20
  persistency: 3
hole_filling:
  enabled: True
  mode: 1

