output_path: "/home/jan/output/TESTING" # path
batch: 8
device: null

# tracking
seg_model: "/home/jan/CORNputer-vision_deployed/post_processing/models/segmentation/segmentation.pt" # path
conf: 0.7 
iou: 0.5 
tracker: "/home/jan/CORNputer-vision_deployed/post_processing/tracker/botsort.yaml" # path, tracking
save_seg_masks: False
seg_masks_visualization: # only relevant if save_seg_masks is True
  show_pixels: True
  show_bboxs: True
  show_conf: True
  color: [[255, 0, 0]]
  overwrite_class: null

# score
alpha: 0.33333 # conf
beta: 0.33333 # center proximity
gamma: 0.33333 # sharpness

# filtering
filter_method: "mean_std" # mad
factor_std: 2.0

# classification
cls_broken_model: "/home/jan/CORNputer-vision_deployed/post_processing/models/classification/broken.pt" # path
cls_tip_model: "/home/jan/CORNputer-vision_deployed/post_processing/models/classification/tip.pt" # path
save_cls_masks: True

# size estimation
size_method: "pca" # mbr
scaling_factor: True
save_size_masks: True
open: 5
close: 5
