data: "/home/jan/datasets/0502_evaluation_broken"
task: "classify" # segment, classify, track
model: "yolo11m-cls"
pretrained: True
output_path: "/home/jan/output/0502"
name: "classification_broken"
device: null
batch: 8

# yolo specific parameters as input for the YOLO.train function
train:
  epochs: 100
  time: null
  patience: 100
  imgsz: 640
  save: True
  save_period: -1
  cache: False
  workers: 1
  exist_ok: False
  pretrained: True
  optimizer: 'auto'
  verbose: False
  seed: 0
  deterministic: True
  single_cls: False #!
  rect: False
  cos_lr: False
  close_mosaic: 10
  resume: False
  amp: True
  fraction: 1.0
  profile: False
  freeze: null
  lr0: 0.01
  lrf: 0.0001
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 5.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  label_smoothing: 0.0
  nbs: 64
  dropout: 0.1
  val: True
  plots: True

# yolo specific parameters as input for the YOLO.train function
augment:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 180.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.5
  fliplr: 0.5
  bgr: 0.0
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
  auto_augment: null
  erasing: 0.4
  crop_fraction: 1.0

# yolo specific parameters as input for the YOLO.val function
val:
  save_txt: True
  save_json: True
  save_hybrid: False
  conf: 0.001
  iou: 0.6
  max_det: 300
  half: True
  dnn: False
  plots: True
  rect: False
  split: "val"

# yolo specific parameters as input for the YOLO.predict / YOLO.track function
infer:
  verbose: False
  conf: 0.25
  iou: 0.5
  half: True
  max_det: 300
  vid_stride: 1
  stream_buffer: False
  visualize: False
  augment: False
  agnostic_nms: False
  classes: null
  retina_masks: False
  embed: null
  show: False
  save: False
  save_txt: False
  save_conf: False
  save_crop: False
  show_labels: True
  show_conf: True
  show_boxes: True
  line_width: null

customArgs:
  trained_model: 'best' # best, last


